/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.13.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as analytics from "../analytics.js";
import type * as appointments from "../appointments.js";
import type * as assessmentQuestions from "../assessmentQuestions.js";
import type * as bookings from "../bookings.js";
import type * as calculateDeposit from "../calculateDeposit.js";
import type * as createBooking from "../createBooking.js";
import type * as estimateServiceDuration from "../estimateServiceDuration.js";
import type * as functions from "../functions.js";
import type * as getAvailableSlots from "../getAvailableSlots.js";
import type * as getCustomizationOptions from "../getCustomizationOptions.js";
import type * as getPolicyDetails from "../getPolicyDetails.js";
import type * as logging from "../logging.js";
import type * as organizationContext from "../organizationContext.js";
import type * as parts from "../parts.js";
import type * as payment from "../payment.js";
import type * as pdfGenerator from "../pdfGenerator.js";
import type * as pdfReports from "../pdfReports.js";
import type * as reportGenerators from "../reportGenerators.js";
import type * as scheduledTasks from "../scheduledTasks.js";
import type * as scheduleReminders from "../scheduleReminders.js";
import type * as services from "../services.js";
import type * as stripe from "../stripe.js";
import type * as userEngagement from "../userEngagement.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  analytics: typeof analytics;
  appointments: typeof appointments;
  assessmentQuestions: typeof assessmentQuestions;
  bookings: typeof bookings;
  calculateDeposit: typeof calculateDeposit;
  createBooking: typeof createBooking;
  estimateServiceDuration: typeof estimateServiceDuration;
  functions: typeof functions;
  getAvailableSlots: typeof getAvailableSlots;
  getCustomizationOptions: typeof getCustomizationOptions;
  getPolicyDetails: typeof getPolicyDetails;
  logging: typeof logging;
  organizationContext: typeof organizationContext;
  parts: typeof parts;
  payment: typeof payment;
  pdfGenerator: typeof pdfGenerator;
  pdfReports: typeof pdfReports;
  reportGenerators: typeof reportGenerators;
  scheduledTasks: typeof scheduledTasks;
  scheduleReminders: typeof scheduleReminders;
  services: typeof services;
  stripe: typeof stripe;
  userEngagement: typeof userEngagement;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
